main :: IO ()
main = writeFile "memory.man" $ unlines $
  [ "      +-------------" ++ concat (replicate 100 "-----") ++ "+"
  , "      | v           " ++ concat (replicate 100 " <   ") ++ "|"
  , "      | s           " ++ concat (replicate 100 " r   ") ++ "|"
  , "      |             " ++ concat (replicate 100 " s   ") ++ "|"
  , "+-+   |             " ++ concat (replicate 100 "> v  ") ++ "|"
  , "|I|>->|@>rbdrb0     " ++ concat (replicate 100 "a^>m ") ++ "|"
  , "+-+   |    >rbrW1   " ++ concat (replicate 100 "dv>m ") ++ "|"
  , "      |             " ++ concat (replicate 100 "> ^  ") ++ "|"
  , "+-+   |             " ++ concat (replicate 100 " s   ") ++ "|"
  , "|O|<-<|             " ++ concat (replicate 100 " W   ") ++ "|"
  , "+-+   |             " ++ concat (replicate 100 " s   ") ++ "|"
  , "      | ^           " ++ concat (replicate 100 " <   ") ++ "|"
  , "      +-------------" ++ concat (replicate 100 "-----") ++ "+"
  , "                    " ++ concat (replicate 100 "v^   ") ++ " "
  , "                    " ++ concat (replicate 100 "||   ") ++ " "
  , "                    " ++ concat (replicate 100 "||   ") ++ " "
  , "                    " ++ concat (replicate 100 "v^   ") ++ " "
  , "                    " ++ concat (replicate 100 "+---+") ++ "+"
  , "                    " ++ concat (replicate 100 "|>@v|") ++ "|"
  , "                    " ++ concat (replicate 100 "|  W|") ++ "|"
  , "                    " ++ concat (replicate 100 "|^<r|") ++ "|"
  , "                    " ++ concat (replicate 100 "| rb|") ++ "|"
  , "                    " ++ concat (replicate 100 "|s^d|") ++ "|"
  , "                    " ++ concat (replicate 100 "|^W<|") ++ "|"
  , "                    " ++ concat (replicate 100 "|---|") ++ "|"
  , "                    " ++ concat (replicate 100 "+---+") ++ "+"
  ]
