name:                icfpc2026
version:             0.1.0.0
github:              "githubuser/icfpc2026"
license:             BSD-3-Clause
author:              "Team Sampou"
maintainer:          "example@example.com"
copyright:           "2026 Team Sampou"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/icfpc2026#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- filepath
- directory
- process
- time

language: GHC2024

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson

executables:
  history-lesson:
    main:               Main.hs
    source-dirs:        app/history-lesson
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2026

  submit:
    main:               Main.hs
    source-dirs:        app/submit
    ghc-options:
    - -rtsopts
    dependencies:
    - icfpc2026

  icfpc2026-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2026
    - dotenv

  add-entry:
    main:                Main.hs
    source-dirs:         app/zzz/add-entry
    dependencies:
    - icfpc2026

tests:
  icfpc2026-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2026
    - dotenv
