on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

name: build
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup-haskell
        name: Setup Haskell
        with:
          ghc-version: 9.10.3
          enable-stack: true
          stack-version: 'latest'
          cabal-update: false

      - name: Setup stack to use system GHC
        run: stack config set system-ghc --global true

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ${{ steps.setup-haskell.outputs.stack-root }}
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.yaml', 'stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-

      - name: Build dependencies
        run: stack build --test --no-run-tests --only-dependencies

      - name: Build
        run: stack build --test --no-run-tests

      - name: Test
        run: stack test
        timeout-minutes: 10
